### ISSUE TITLE
zip command not found

### ISSUE THREAD

**Issue by AntoninoBonanno** [semantic-release/wordpress#199]
If the zip command is not present this code will return an error but `packageResult.stderr` is empty and the publish stage will be triggered anyway. 
Then it shows an error on the screen that is not easily understandable.

https://github.com/semantic-release/wordpress/blob/e8b42e55b94b8431fcc90048c2cad167357511f3/lib/publish.ts#L18-L35

It would be a good idea to check whether the `zip` command is already present during the verification phase.

**Comment by seebeen** [comment]
Since the publish stage is meant to be run in a CI environment, and as far as I know, all of CI environments have some semblance of a zip command - I thought the check is unnecessary.

@travi - Thoughts?

**Comment by AntoninoBonanno** [comment]
@seebeen in my CI I had to configure like this to make it work

```
release:
  image: node:20
  stage: release
  before_script:
    - apt-get update
    - apt-get install -y zip
  script:
  ...
```
